# Generated by Django 5.0 on 2023-12-29 22:04

import django.db.models.deletion
import django_choices_field.fields
from django.db import migrations
from django.db import models

import gifts.apps.gifts.models


class Migration(migrations.Migration):
    dependencies = [
        ("gifts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="giftorder",
            name="is_confirmed_by_admin",
        ),
        migrations.RemoveField(
            model_name="historicalgiftorder",
            name="is_confirmed_by_admin",
        ),
        migrations.AddField(
            model_name="giftorder",
            name="status",
            field=django_choices_field.fields.TextChoicesField(
                choices=[
                    ("pending", "Pending"),
                    ("withdrawn", "Withdrawn"),
                    ("confirmed", "Confirmed"),
                ],
                choices_enum=gifts.apps.gifts.models.OrderStatus,
                default="pending",
                max_length=9,
            ),
        ),
        migrations.AddField(
            model_name="historicalgiftorder",
            name="status",
            field=django_choices_field.fields.TextChoicesField(
                choices=[
                    ("pending", "Pending"),
                    ("withdrawn", "Withdrawn"),
                    ("confirmed", "Confirmed"),
                ],
                choices_enum=gifts.apps.gifts.models.OrderStatus,
                default="pending",
                max_length=9,
            ),
        ),
        migrations.AlterField(
            model_name="gift",
            name="description_full",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="giftorder",
            name="gift",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                related_query_name="order",
                to="gifts.gift",
            ),
        ),
        migrations.AlterField(
            model_name="historicalgift",
            name="description_full",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="historicalgiftorder",
            name="gift",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="order",
                to="gifts.gift",
            ),
        ),
    ]
