# Generated by Django 5.0 on 2023-12-29 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gifts", "0002_add_field_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalgiftorder",
            name="gift",
        ),
        migrations.AlterField(
            model_name="giftorder",
            name="gift",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order",
                related_query_name="order",
                to="gifts.gift",
            ),
        ),
    ]
