# Generated by Django 5.0 on 2024-01-05 14:55

import django.core.validators
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("gifts", "0003_alter_order_to_o2o"),
    ]

    operations = [
        migrations.AddField(
            model_name="gift",
            name="order_amount_default",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="giftorder",
            name="amount",
            field=models.IntegerField(
                default=1, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AddField(
            model_name="historicalgift",
            name="order_amount_default",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="historicalgiftorder",
            name="amount",
            field=models.IntegerField(
                default=1, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
    ]
