# Generated by Django 5.0 on 2024-01-05 19:54

import django_choices_field.fields
from django.db import migrations

import gifts.apps.gifts.models


class Migration(migrations.Migration):
    dependencies = [
        ("gifts", "0005_alter_gift_points_decimal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="giftorder",
            name="status",
            field=django_choices_field.fields.TextChoicesField(
                choices=[
                    ("submitted", "Submitted"),
                    ("withdrawn", "Withdrawn"),
                    ("confirmed", "Confirmed"),
                ],
                choices_enum=gifts.apps.gifts.models.OrderStatus,
                default="submitted",
                max_length=9,
            ),
        ),
        migrations.AlterField(
            model_name="historicalgiftorder",
            name="status",
            field=django_choices_field.fields.TextChoicesField(
                choices=[
                    ("submitted", "Submitted"),
                    ("withdrawn", "Withdrawn"),
                    ("confirmed", "Confirmed"),
                ],
                choices_enum=gifts.apps.gifts.models.OrderStatus,
                default="submitted",
                max_length=9,
            ),
        ),
    ]
