# Generated by Django 5.0 on 2024-01-05 23:03

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("gifts", "0006_alter_field_gift_order_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gift",
            name="image_card",
        ),
        migrations.RemoveField(
            model_name="historicalgift",
            name="image_card",
        ),
        migrations.AddField(
            model_name="giftimage",
            name="is_primary",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalgiftimage",
            name="is_primary",
            field=models.BooleanField(default=False),
        ),
    ]
