# Generated by Django 5.0.1 on 2024-01-06 17:22

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("gifts", "0007_remove_gift_image_card_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="giftimage",
            options={"ordering": ["order"]},
        ),
        migrations.RemoveField(
            model_name="giftimage",
            name="is_primary",
        ),
        migrations.RemoveField(
            model_name="historicalgiftimage",
            name="is_primary",
        ),
        migrations.AddField(
            model_name="giftimage",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="historicalgiftimage",
            name="order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="giftimage",
            name="caption",
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name="giftimage",
            name="gift",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="gifts.gift",
            ),
        ),
        migrations.AlterField(
            model_name="historicalgiftimage",
            name="caption",
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
